---
title: "lit_review_interactions"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(janitor)
library(ordinal)
library(emmeans)
library(blme)
library(lme4)

```

# Read Data 

```{r}

data <- read.delim("lit_review_interactions.csv", sep = ",")
data <- clean_names(data)
head(data)

```

Select relevant columns. 

```{r}

data_original <- data %>% dplyr::select(obs_id, title, sample_size, response_type, response_category, local_strategy, simple, intermediate, complex)
head(data_original)

```

Ensure columns are factors. 

```{r}

data_original <- data_original %>% 
  mutate(obs_id = as.factor(obs_id)) %>%
  mutate(title = as.factor(title)) %>% 
  mutate(response_type = as.factor(response_type)) %>% 
  mutate(response_category = as.factor(response_category)) %>% 
  mutate(local_strategy = as.factor(local_strategy)) %>% 
  mutate(simple = as.factor(simple)) %>% 
  mutate(intermediate = as.factor(intermediate)) %>% 
  mutate(complex = as.factor(complex))
head(data_original)

```

Pivot data frame to create landscape category and response columns.

```{r}

data_original <- data_original %>% 
  pivot_longer(
    cols = c('simple', 'intermediate', 'complex'), 
    names_to = "landscape_cat", 
    values_to = "response"
  )
head(data_original)

```

```{r}

data_original <- data_original %>% 
  mutate(response = as.factor(response)) %>%
  mutate(landscape_cat = as.factor(landscape_cat))
head(data_original)

```

```{r}

data_collapsed <- data %>% select(obs_id, title, sample_size, response_type, response_category, local_strategy, simple_collapsed, intermediate_collapsed, complex_collapsed)
head(data_collapsed)

```

```{r}

data_collapsed <- data_collapsed %>% 
  mutate(obs_id = as.factor(obs_id)) %>%
  mutate(title = as.factor(title)) %>% 
  mutate(response_type = as.factor(response_type)) %>% 
  mutate(response_category = as.factor(response_category)) %>% 
  mutate(local_strategy = as.factor(local_strategy)) %>% 
  mutate(simple_collapsed = as.factor(simple_collapsed)) %>% 
  mutate(intermediate_collapsed = as.factor(intermediate_collapsed)) %>% 
  mutate(complex_collapsed = as.factor(complex_collapsed)) %>%
  rename(simple = simple_collapsed, intermediate = intermediate_collapsed, complex = complex_collapsed)

head(data_collapsed)

```

```{r}

data_collapsed <- data_collapsed %>% 
  pivot_longer(
    cols = c('simple', 'intermediate', 'complex'), 
    names_to = "landscape_cat", 
    values_to = "response"
  )
head(data_collapsed)

```

# Models

Models for original data. 

```{r}

model <- clmm(response ~ landscape_cat*local_strategy + (1|title) + (1|local_strategy), data = data_original)	
summary(model)

```

```{r}

model.posthoc <- emmeans(model, "landscape_cat", data=data_original)
pairs(model.posthoc, adjust="tukey")

```

```{r}

plot(model.posthoc, comparisons = TRUE)

```


```{r}

model <- clmm(response ~ landscape_cat*response_type + landscape_cat*local_strategy + (1|title), data = data_original)	
summary(model)

```

```{r}

model.posthoc <- emmeans(model, "landscape_cat", data=data_original)
pairs(model.posthoc, adjust="tukey")

```

```{r}

plot(model.posthoc, comparisons = TRUE)

```


```{r}

model <- clmm(response ~ landscape_cat*response_type + landscape_cat*local_strategy + (1|title), data = data_original, weights = sample_size)	
summary(model)

```

Models for collapsed data - blme.

bglmer(response ~ landscape_cat*local_strategy + (1|title) + (1|obs_id),

                data = data_collapsed, family='binomial',

                control=glmerControl(optimizer="bobyqa"),

                fixef.prior = normal(cov = diag(100, 12)))

```{r}

model <- bglmer(response ~ landscape_cat*local_strategy + (1|title) + (1|obs_id), data = data_collapsed, family='binomial', control=glmerControl(optimizer="bobyqa"), fixef.prior = normal(cov = diag(100, 12)))	
summary(model)

```



