---
title: "2022_scm_analysis_models"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(fitdistrplus)
library(lme4)

```

```{r}

scm_climate_df <- read.delim("Dataframes/scm_model.csv", sep = ",")
scm_climate_df$date <- ymd(scm_climate_df$date)
scm_climate_df$record_id <- as.factor(scm_climate_df$record_id)
scm_climate_df

```

```{r}

scm_practice_df <- read.delim("Dataframes/scm_model_practices.csv", sep = ",")
#scm_practice_df$date <- ymd(scm_climate_df$date)
scm_practice_df$cover_crop <- as.factor(scm_practice_df$cover_crop)
scm_practice_df$manure <- as.factor(scm_practice_df$manure)

scm_practice_df

```

```{r}

scm_max_df <- read.delim("Dataframes/scm_max_counts.csv", sep = ",")
#scm_practice_df$date <- ymd(scm_climate_df$date)
#scm_practice_df$record_id <- as.factor(scm_climate_df$record_id)
scm_max_df

```

```{r}

scm_500_df <- read.delim("Dataframes/scm_500.csv", sep = ",")
scm_500_df$date <- ymd(scm_500_df$date)
scm_500_df$record_id <- as.factor(scm_500_df$record_id)
scm_500_df$cover_crop <- as.factor(scm_500_df$cover_crop)
scm_500_df$manure <- as.factor(scm_500_df$manure)

scm_500_df

```

```{r}

plot(fitdist(c(na.exclude(scm_climate_df$count)),"nbinom"))

```

Response - Counts.
Features - Climate. 
Random Effect - Site.

```{r}

model <- glmer.nb(count ~ scale(week) + scale(max_temp_f) + scale(min_temp_f) + scale(rain_inches) + (1 | record_id), data = scm_climate_df)
summary(model)

```

Response - Count.
Features - Climate and broad landscape categories.
Random Effect - Site.

```{r}

model <- glmer.nb(count ~ scale(week) + scale(max_temp_f) + scale(min_temp_f) + scale(rain_inches) + scale(ag_prop) + scale(nat_prop) + scale(semi_nat_prop) + (1 | record_id), data = scm_500_df)
summary(model)

```

Response - Count.
Features - Relative planting week, climate.
Random Effect - Site. 

```{r}

model <- glmer.nb(count ~ scale(week) + planting_relative_week + scale(max_temp_f) + scale(min_temp_f) + scale(rain_inches) + (1 | record_id), data = scm_practice_df)
summary(model)

```

```{r}

plot(scm_practice_df$count, scm_practice_df$planting_relative_week)

```

```{r}

hist(log(scm_max_df$count))

```

```{r}

plot(fitdist(c(na.exclude(scm_max_df$count)),"lnorm"))

```

Not enough observations to converge model for maximum counts. 

```{r}

model <- glmer(count ~ scale(week) + planting_relative_week + scale(max_temp_f) + scale(min_temp_f) + scale(rain_inches) + (1 | record_id), family= gaussian(link='log'), data = scm_max_df)
summary(model)

```

```{r}

model <- glmer.nb(count ~ scale(week) + planting_relative_week + scale(max_temp_f) + scale(min_temp_f) + scale(rain_inches) + cover_crop + manure + (1 | record_id), data = scm_practice_df)
summary(model)

```









