---
title: "scm_emergence_review"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) 
```


```{r}

n_fields <- 25 # 25 fields sampled
n_traps_per_field <- 2 # 2 sticky traps per field
n_samples <- 6  # 6 weeks of servicing traps once per week
first_emergence_mean <- 103 # average of first emergence degree-day
first_emergence_SE <- 8 # standard error of first emergence degree-day
first_emergence_SD <- first_emergence_SE * sqrt(n_fields) # calculate standard deviation of first emergence (SE = SD / sqrt(n))

first_emergence_DD <- rnorm(n_fields, mean = first_emergence_mean, sd = first_emergence_SD) # simulate DD distribution

min_first_emergence <- 57 # minimum reported in paper
max_first_emergence <- 197 # maximum reported in paper

max(first_emergence_DD) # 180

min(first_emergence_DD) # 20

```


```{r}

sim_data <- function(n, mean, sd, seed){
  set.seed(seed)
  tibble(DD = rnorm(n, mean, sd))
}

```

```{r}

random_DD <- sim_data(n = 1000,    #arbitrary sample size
         mean = 10,   #arbitrary average
         sd = 2,      #arbitrary standard deviation
         seed = 1) #set seed for reproducibility

ggplot(random_DD, aes(x = DD)) +
  geom_histogram(binwidth = 1) +
  geom_vline(xintercept = min(random_DD$DD), color = "green") + # minimum value
  geom_vline(xintercept = mean(random_DD$DD), color = "blue") + # average value
  labs(y = "Count or abundance")


```

```{r}

historical_mean_peak <- 360

historical_simulations <- tibble(
  total_fields = 1000, # number of fields sampled to calculate average (could be larger or smaller)
  avg = historical_mean_peak,
  sd = seq(from = 10, to = 100, length.out = 10) # ten values from 10 to 100 to be used as the standard deviations of the distributions of DDs per field
) %>%
  expand_grid(sim = c(1:1000)) %>% # 1000 simulations
  rowwise() %>% # perform following operations for each row 
  mutate(emergence_data = list(sim_data(n = total_fields, mean = avg, sd = sd, seed = sim))) %>% # create distributions of DDs for 1000 fields with varying standard deviations
  mutate(min_emergence = min(emergence_data), # obtain minimal value of distributions per simulation
         mean_emergence = mean(emergence_data$DD)) %>% # obtain average value of distributions per simulation
  ungroup()

ggplot(historical_simulations, aes(x = min_emergence)) +
  geom_histogram() +
  geom_vline(xintercept = first_emergence_mean, color = "green") + # Cho et al. reported average
  geom_vline(xintercept = first_emergence_mean + (1.96*first_emergence_SD), linetype = 2) + # upper-bound of 95% confidence interval around the mean reported by Cho et al.
  geom_vline(xintercept = first_emergence_mean - (1.96*first_emergence_SD), linetype = 2) + # lower-bound of 95% confidence interval around the mean reported by Cho et al.
  facet_wrap(~ sd) + # facet by standard deviation of simulated DDs
  coord_cartesian(xlim = c(0,350)) +
  labs(x = "First emergence DD")

```
```{r}

ggplot(historical_simulations, aes(x = mean_emergence)) +
  geom_histogram() +
  geom_vline(xintercept = first_emergence_mean, color = "green") +
  geom_vline(xintercept = first_emergence_mean + (1.96*first_emergence_SD), linetype = 2) +
  geom_vline(xintercept = first_emergence_mean - (1.96*first_emergence_SD), linetype = 2) +
  facet_wrap(~ sd) +
  labs(x = "Peak adult activity DD")

```

```{r}

# function to simulate averages
sim_data2 <- function(n, mean, sd, seed){
  set.seed(seed)
  rnorm(n, mean, sd)
}

historical_simulations2 <- tibble(sd_avg = seq(from = 0.5, to = 40, length.out = 5)) %>% # range of certainty around the mean
  expand_grid(sim = c(1:1000)) %>%
  rowwise() %>%
  mutate(avg = sim_data2(n = 1, mean = 360, sd = sd_avg, seed = sim)) %>% # generate means from a normal distribution with different degrees of variation
  expand_grid(sd_obs = seq(from = 10, to = 100, length.out = 5))  %>% # generate only five levels of variation in the distribution of observed DDs for simplicity
  rowwise() %>%
  mutate(emergence_data = list(sim_data(n = 1000, mean = avg, sd = sd_obs, seed = sim))) %>%
  mutate(avg_obs = mean(emergence_data$DD),
         min_obs = min(emergence_data$DD)) %>%
  ungroup()

ggplot(historical_simulations2, aes(x = avg_obs)) +
  geom_histogram() +
  geom_vline(xintercept = first_emergence_mean, color = "green") +
  geom_vline(xintercept = first_emergence_mean + (1.96*first_emergence_SD), linetype = 2) +
  geom_vline(xintercept = first_emergence_mean - (1.96*first_emergence_SD), linetype = 2) +
  facet_grid(sd_obs~sd_avg)+ # columns are certainty levels, rows are observational variations
  labs(x = "Peak adult activity DD")

```

```{r}

ggplot(historical_simulations2, aes(x = min_obs)) +
  geom_histogram() +
  geom_vline(xintercept = first_emergence_mean, color = "green") +
  geom_vline(xintercept = first_emergence_mean + (1.96*first_emergence_SD), linetype = 2) +
  geom_vline(xintercept = first_emergence_mean - (1.96*first_emergence_SD), linetype = 2) +
  facet_grid(sd_obs~sd_avg) + # columns are certainty levels, rows are observational variations
  coord_cartesian(xlim = c(0, 400))+
  labs(x = "First emergence DD")


```
