---
title: "swd_models"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)
library(fitdistrplus)
library(lme4)
library(Boruta)
library(sjPlot)
library(jtools)
library(interactions)
library(DHARMa)
library(rsq)
library(effects)
library(pscl)
library(glmmTMB)
library(emmeans)
library(car)

```

Link with hurdle model - https://stats.oarc.ucla.edu/wp-content/uploads/2024/03/Zero_inf_2024_2.html#1 

Helpful vingette for glmmTMB - https://www.biorxiv.org/content/biorxiv/suppl/2017/05/01/132753.DC1/132753-2.pdf 

```{r}

subset_2024 <- read.delim("Data/subset_2024.csv", sep = ",")
subset_2024

```

```{r}

subset_2024 <- subset_2024 %>%
  mutate(collection_date = as.Date(collection_date, '%Y-%m-%d')) %>%
  mutate_at(c('farm', 'name', 'host_plant', 'blueberry_family'), as.factor) 

```


```{r}

plot(fitdist(subset_2024$lj_sum,"nbinom"))

```

```{r}

zinbinom <- glmmTMB(lj_sum ~  forest_prop + collection_date + swd_sum + blueberry_family + (1|name),
                      data=subset_2024,
                      ziformula= ~forest_prop + collection_date + swd_sum + blueberry_family,
                      family=nbinom2)

summary(zinbinom)

```

```{r}

zinbinom <- glmmTMB(lj_sum ~  swd_sum + (1|name),
                      data=subset_2024,
                      ziformula= ~swd_sum + (1|name),
                      family=nbinom2)

summary(zinbinom)

```

```{r}

m1 <- glmmTMB(presence_lj ~ forest_prop + ag_prop + collection_date + swd_sum + blueberry_family + (1|name), family=binomial, data=subset_2024)

summary(m1)

```

```{r}

present <- subset_2024 %>% filter(presence_lj == 1)

hist(present$lj_sum)
  
m2 <- glmmTMB(lj_sum ~ forest_prop + ag_prop + collection_date + swd_sum + blueberry_family + (1|name), family=nbinom2, data=present)

summary(m2)

```


