---
title: "lit_review_interactions"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(janitor)
library(ordinal)
library(emmeans)
library(blme)
library(lme4)
library(sjPlot)
library(sjmisc)
library(interactions)
library(effects)
library(DHARMa)
library(styler)

```

Read data.

```{r}

data <- read.delim("Data/Interaction_Analyses/lit_review_interactions.csv",
                   sep = ",")
data <- clean_names(data)
head(data)

```

```{r}

data_collapsed <- data %>% dplyr::select(
  obs_id,
  title,
  response_type,
  response_category,
  local_strategy,
  simple_collapsed,
  intermediate_collapsed,
  complex_collapsed
)
head(data_collapsed)

```

```{r}

data_collapsed <- data_collapsed %>%
  mutate(obs_id = as.factor(obs_id)) %>%
  mutate(title = as.factor(title)) %>%
  mutate(response_type = as.factor(response_type)) %>%
  mutate(response_category = as.factor(response_category)) %>%
  mutate(local_strategy = as.factor(local_strategy)) %>%
  mutate(simple_collapsed = as.factor(simple_collapsed)) %>%
  mutate(intermediate_collapsed = as.factor(intermediate_collapsed)) %>%
  mutate(complex_collapsed = as.factor(complex_collapsed)) %>%
  dplyr::rename(simple = simple_collapsed,
                intermediate = intermediate_collapsed,
                complex = complex_collapsed)

```

```{r}

data_collapsed <- data_collapsed %>%
  pivot_longer(
    cols = c('simple', 'intermediate', 'complex'),
    names_to = "landscape_cat",
    values_to = "response"
  )
head(data_collapsed)

```

# Models

Mixed-effects logistic regression models.

### All Significant Interactions 

Referred to as "Model 1" in the paper.

```{r}

model <- bglmer(
  response ~ landscape_cat * local_strategy - 1 + (1 | title) + (1 | obs_id),
  data = data_collapsed,
  family = 'binomial',
  control = glmerControl(optimizer = "bobyqa"),
  fixef.prior = normal(cov = diag(100, 12))
)
summary(model)

res <- simulateResiduals(model)
plot(res)

```

### Recategorized Interactions

Referred to as "Model 2" in the paper.

```{r}

recat <- read.delim("Data/Interaction_Analyses/lit_review_recat_for_analysis.csv", sep = ",")
recat <- clean_names(recat)
head(recat)

```

```{r}

recat$response[recat$response == 'neg'] <- 'np'
recat$response[recat$response == 'ns'] <- 'np'

```

```{r}

recat <- recat %>% 
  mutate(local_strategy = as.factor(local_strategy)) %>%
  mutate(landscape = as.factor(landscape)) %>% 
  mutate(response = as.factor(response)) %>%
  mutate(obs_id = as.factor(obs_id))
head(recat)

```

```{r}

model <- bglmer(
  response ~ landscape * local_strategy - 1 + (1 | title) + (1 | obs_id),
  data = recat,
  family = 'binomial',
  control = glmerControl(optimizer = "bobyqa"),
  fixef.prior = normal(cov = diag(100, 12))
)
summary(model)

```

### Recategorized Interactions (Europe)

Referred to as "Model 3" in the paper.

```{r}

recat_europe <- read.delim("Data/Interaction_Analyses/lit_review_recat_europe_for_analysis.csv", sep = ",")
recat_europe <- clean_names(recat_europe)
head(recat_europe)

```

```{r}

recat_europe$response[recat_europe$response == 'neg'] <- 'np'
recat_europe$response[recat_europe$response == 'ns'] <- 'np'

```

```{r}

recat_europe <- recat_europe %>% 
  mutate(local_strategy = as.factor(local_strategy)) %>%
  mutate(landscape = as.factor(landscape)) %>% 
  mutate(response = as.factor(response)) %>%
  mutate(obs_id = as.factor(obs_id))
head(recat_europe)

```

```{r}

model_europe <- bglmer(response ~ landscape*local_strategy - 1 + (1|title) + (1|obs_id), data = recat_europe, family='binomial', control=glmerControl(optimizer="bobyqa"), fixef.prior = normal(cov = diag(100, 8)))	
summary(model_europe)

```

### Recategorized Interactions (North America)

Referred to as "Model 4" in the paper.

```{r}

recat_na <- read.delim("Data/Interaction_Analyses/lit_review_recat_na_for_analysis.csv", sep = ",")
recat_na <- clean_names(recat_na)
head(recat_na)

```

```{r}

recat_na$response[recat_na$response == 'neg'] <- 'np'
recat_na$response[recat_na$response == 'ns'] <- 'np'

```

```{r}

recat_na <- recat_na %>% 
  mutate(local_strategy = as.factor(local_strategy)) %>%
  mutate(landscape = as.factor(landscape)) %>% 
  mutate(response = as.factor(response)) %>%
  mutate(obs_id = as.factor(obs_id))
head(recat_na)

```

```{r}

model_na <- bglmer(response ~ landscape*local_strategy - 1 + (1|title) + (1|obs_id), data = recat_na, family='binomial', control=glmerControl(optimizer="bobyqa"), fixef.prior = normal(cov = diag(100, 12)))	
summary(model_na)

```


