---
title: "2023_scm_wire_mesh_models"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)
library(fitdistrplus)
library(lme4)
library(Boruta)
library(sjPlot)

set.seed(42)
```

```{r}

adult_features <- read.delim("Data/2023_adult_features.csv", sep = ",")
adult_features

```

```{r}

management <- read.delim("Data/2023_management.csv", sep = ",")
management

```

```{r}

adult_features <- adult_features %>%
  mutate(collection_date = as.Date(collection_date, '%Y-%m-%d')) %>%
  mutate_at(c('card_id', 'record_id', 'data_collector', "previous_crop", "cover_crop", "manure", "tillage", "ny_soils_0", "ny_soils_01", "muid","hsg", "hsgint"), as.factor) %>%
  dplyr::select(-c(X, card_id, n_scm_i_m, n_scm_i_f, n_scm_o_m, n_scm_o_f, n_d_florilega_i, n_d_florilega_o, total_f_scm, total_m_scm))

```

```{r}

plot(fitdist(adult_features$total_scm,"nbinom"))

```

```{r}

boruta <- Boruta(total_scm ~ ., data = na.exclude(adult_features), doTrace = 2, maxRuns = 500)
print(boruta)

plot(boruta, las = 2, cex.axis = 0.7)

```

```{r}

features <- getSelectedAttributes(boruta, withTentative = F)
features

```

'nat_prop_2018_500', 'ag_prop_2019_500', 'nat_prop_2019_500',
       'semi_nat_prop_2 year_2000', 'wheat_prop_2018_3000',
       'total_nat_prop_2018_3000', 'nat_prop_2019_3000',
       'wheat_prop_2019_3000', 'ag_prop_3 year_3000',
       'total_nat_prop_4 year_3000'

```{r}

df <- adult_features %>% 
  dplyr::select(c(total_scm, record_id, features)) %>%
  dplyr::select(-collection_date)

model <- glmer.nb(total_scm ~ . + (1 | record_id), data = df)

summary(model)

```

```{r}

model <- glmer.nb(total_scm ~ scale(collection_date) + longitude + latitude + cover_crop + manure + ave_temp_f_1_week + rain_inches_1_week + corn_prop_5.year_500 + soybean_prop_5.year_500 + forest_prop_5.year_500 + organic_matter_percent + (1 | record_id), data = adult_features)

summary(model)

```
```{r}

model <- glmer.nb(total_scm ~ scale(collection_date) + longitude + latitude + cover_crop + manure + ave_temp_f_1_week + rain_inches_1_week + corn_prop_5.year_500 + soybean_prop_5.year_500 + wheat_prop_5.year_1000 + organic_matter_percent + (1 | record_id), data = adult_features)

summary(model)

```


```{r, fig.width=6, fig.height=6}

sjPlot::plot_model(model, 
                   show.values=TRUE, show.p=TRUE,
                   title="Effect on SCM Adults")

```


```{r}

peak_adults <- read.delim("Data/2023_adult_peak_features.csv", sep = ",")
peak_adults

```

```{r}

peak_adults <- peak_adults %>%
  mutate(collection_date = as.Date(collection_date, '%Y-%m-%d')) %>%
  mutate_at(c('record_id', 'data_collector', "previous_crop", "cover_crop", "manure", "tillage", "ny_soils_0", "ny_soils_01", "muid","hsg", "hsgint"), as.factor) %>%
  dplyr::select(-c(X, n_scm_i_m, n_scm_i_f, n_scm_o_m, n_scm_o_f, n_d_florilega_i, n_d_florilega_o, total_f_scm, total_m_scm))

```

```{r}

plot(fitdist(peak_adults$total_scm,"norm"))

```

```{r}

boruta <- Boruta(total_scm ~ ., data = na.exclude(peak_adults), doTrace = 2, maxRuns = 500)
print(boruta)

plot(boruta, las = 2, cex.axis = 0.7)

```

```{r}

features <- getSelectedAttributes(boruta, withTentative = F)
features

```

```{r}

model <- glm(total_scm ~ scale(collection_date) + longitude + latitude + cover_crop + manure + ave_temp_f_1_week + rain_inches_1_week + corn_prop_5.year_500 + soybean_prop_5.year_500 + wheat_prop_5.year_1000 + organic_matter_percent, data = peak_adults, family = gaussian)
summary(model)

```















