---
title: "2023_scm_wire_mesh_models"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)
library(fitdistrplus)
library(Boruta)

```

```{r}

wire_mesh_features <- read.delim("Data/2023_wire_mesh_features.csv", sep = ",")
wire_mesh_features

```

```{r}

wire_mesh_features <- wire_mesh_features %>%
  mutate(collection_date = as.Date(collection_date, '%m/%d/%y')) %>%
  mutate_at(c('seed_type', 'record_id'), as.factor) %>%
  dplyr::select(-c(total_scm_maggots, total_scm_pupae, scm_seeds, id, container_number, project))

```

```{r}

colnames(wire_mesh_features)

```


```{r}

plot(fitdist(wire_mesh_features$total_scm,"nbinom"))

```


```{r}

boruta <- Boruta(total_scm ~ ., data = na.exclude(wire_mesh_features), doTrace = 2, maxRuns = 500)
print(boruta)

plot(boruta, las = 2, cex.axis = 0.7)

```


```{r}

features <- getSelectedAttributes(boruta, withTentative = F)
features

```


```{r}

df <- wire_mesh_features %>% 
  dplyr::select(c(total_scm, record_id, features)) 

model <- glmer.nb(total_scm ~ . + (1 | record_id), data = df)

summary(model)

```











