---
title: "2023_2024_scm_adult_models"
author: "Chloe Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)
library(fitdistrplus)
library(lme4)
library(Boruta)
library(sjPlot)
library(jtools)
library(interactions)
library(DHARMa)
library(rsq)
library(effects)
library(readxl)
library(MuMIn)

set.seed(42)
```

```{r}

adult_features <- read.delim("all_features_2023_2024_scm_adults.csv", sep = ",")
adult_features

```

```{r}

adult_features <- adult_features %>%
  mutate(date_collected = as.Date(date_collected, '%Y-%m-%d')) %>%
  mutate(planting_date = as.Date(planting_date, '%Y-%m-%d')) %>%
  mutate_at(c('field_id', "previous_crop", "cover_crop", "manure", "tillage"), as.factor) %>% 
  dplyr::select(-c('card_id', 'X', 'total_scm', 'scm_male', 'scm_female', 'florilega', 'season_total', 'male_total', 'female_total', 'weekly_prop', 
            'weekly_prop_f', 'weekly_prop_m', 'season_prop'))
adult_features

```

```{r}

adult_features_selected <- adult_features %>%
  mutate(date_collected = as.Date(date_collected, '%Y-%m-%d')) %>%
  mutate_at(c('field_id', "previous_crop", "cover_crop", "manure", "tillage"), as.factor) %>% 
  dplyr::select(-c('prop_corn_previous_year_500m',
       'prop_ag_previous_year_500m', 'prop_nat_previous_year_500m','prop_corn_current_year_500m',
       'prop_ag_current_year_500m', 'prop_nat_current_year_500m'))
adult_features_selected

```

```{r}

plot(fitdist(adult_features$total_flies,"nbinom"))

```

```{r}
# Boruta with all features 

boruta <- Boruta(total_flies ~ ., data = na.exclude(adult_features), doTrace = 2, maxRuns = 500)
print(boruta)

png("boruta.png", width = 8, height = 6, units = "in", res = 300)
plot(boruta, las = 2, cex.axis = 0.35)

```

Dispersal (~1km/day before oviposition) - https://onlinelibrary.wiley.com/doi/10.1111/j.1570-7458.2012.01271.x
https://www.researchgate.net/publication/230003215_Dispersal_of_cabbage_root_fly

```{r}

features <- getSelectedAttributes(boruta, withTentative = F)
features

```


```{r}
# Boruta with selected features 

boruta <- Boruta(total_flies ~ ., data = na.exclude(adult_features_selected), doTrace = 2, maxRuns = 500)
print(boruta)

plot(boruta, las = 2, cex.axis = 0.45)

```

```{r}

features <- getSelectedAttributes(boruta, withTentative = T)
features

```

```{r}

adult_features <- adult_features %>%
    mutate(previous_crop = case_when(previous_crop == 'Silage Corn' ~ 'Corn',
                           previous_crop == 'Grain Corn' ~ 'Corn',
                           previous_crop == 'Soybean' ~ 'Soybean',
                           TRUE ~ 'Other'))
  

```


```{r}

model1 <- glmer.nb(total_flies ~ scale(date_collected) + cover_crop + previous_crop + scale(ppt_in) + scale(tmean_f) + scale(prop_corn_current_year_1000m) + scale(prop_ag_current_year_1000m) + scale(prop_nat_current_year_1000m) + scale(planting_date) + (1 | field_id), data = adult_features)

summary(model1)

```

```{r}

model2 <- glmer.nb(total_flies ~ scale(date_collected) + cover_crop + previous_crop + scale(tmean_f) + scale(prop_corn_current_year_1000m) + scale(prop_nat_current_year_1000m) + scale(planting_date) + (1 | field_id), data = adult_features)

summary(model2)

```

Climate * landscape
Management * landscape
Climate * management

```{r}

model3 <- glmer.nb(total_flies ~ scale(date_collected) + 
                     cover_crop + 
                     previous_crop + 
                     scale(tmean_f) + 
                     scale(prop_corn_current_year_1000m) + 
                     scale(prop_nat_current_year_1000m) + 
                     scale(planting_date) + 
                     scale(tmean_f) * scale(prop_corn_current_year_1000m) + 
                     scale(tmean_f) * scale(prop_nat_current_year_1000m) + 
                     cover_crop * scale(prop_corn_current_year_1000m) + 
                     cover_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(prop_corn_current_year_1000m) + 
                     previous_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(tmean_f) + 
                     scale(tmean_f) * cover_crop + 
                     (1 | field_id), data = adult_features)

summary(model3)

```

```{r}

options(na.action = "na.fail")
model3_dredge <- dredge(model3)
nrow(model3_dredge)
model3_dredge[1,]

best3 <- get.models(model3_dredge, delta==0)[[1]]
summary(best3)

```

```{r}

corn_effect <- predictorEffect("prop_corn_current_year_1000m", best3)
plot(corn_effect)

```

```{r}

adult_features$date_collected_numeric <- as.numeric(adult_features$date_collected)

corn_effect <- predictorEffect("prop_corn_current_year_1000m", best3)
plot(corn_effect)

```
Temperature does not interact with management. 

```{r}

model4 <- glmer.nb(total_flies ~ scale(date_collected) + cover_crop + previous_crop + scale(tmean_f) + scale(prop_corn_current_year_1000m) + scale(prop_nat_current_year_1000m) + scale(planting_date) + scale(tmean_f) * scale(prop_corn_current_year_1000m) + cover_crop * scale(prop_corn_current_year_1000m) + previous_crop * scale(prop_corn_current_year_1000m) + (1 | field_id), data = adult_features)

summary(model4)

```

```{r}

options(na.action = "na.fail")
model4_dredge <- dredge(model4)
nrow(model4_dredge)
model4_dredge[1,]

best4 <- get.models(model4_dredge, delta==0)[[1]]
summary(best4)

```


```{r}

options(na.action = "na.omit")
model5 <- glmer.nb(total_flies ~ scale(date_collected_numeric) + 
                     cover_crop + 
                     previous_crop + 
                     scale(tmean_f) + 
                     scale(prop_corn_current_year_1000m) + 
                     scale(prop_nat_current_year_1000m) + 
                     scale(planting_date) + 
                     scale(tmean_f) * scale(prop_corn_current_year_1000m) + 
                     scale(tmean_f) * scale(prop_nat_current_year_1000m) + 
                     cover_crop * scale(prop_corn_current_year_1000m) + 
                     cover_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(prop_corn_current_year_1000m) + 
                     previous_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(tmean_f) + 
                     scale(tmean_f) * cover_crop + 
                     (1 | field_id), data = adult_features)

summary(model5)

```

```{r}

options(na.action = "na.omit")
model6 <- glmer.nb(total_flies ~ scale(date_collected_numeric) + 
                     cover_crop + 
                     previous_crop + 
                     scale(tmean_f) + 
                     scale(prop_corn_current_year_1000m) + 
                     scale(prop_nat_current_year_1000m) + 
                     scale(planting_date) + 
                     scale(tmean_f) * scale(prop_corn_current_year_1000m) + 
                     scale(tmean_f) * scale(prop_nat_current_year_1000m) + 
                     cover_crop * scale(prop_corn_current_year_1000m) + 
                     cover_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(prop_corn_current_year_1000m) + 
                     previous_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(tmean_f) + 
                     scale(tmean_f) * cover_crop + 
                     (1 | field_id) + (1 | year), data = adult_features)

summary(model6)

```

```{r}

options(na.action = "na.omit")
model7 <- glmer.nb(total_flies ~ scale(date_collected_numeric) + 
                     cover_crop + 
                     previous_crop + 
                     scale(year) +
                     scale(tmean_f) + 
                     scale(prop_corn_current_year_1000m) + 
                     scale(prop_nat_current_year_1000m) + 
                     scale(planting_date) + 
                     scale(tmean_f) * scale(prop_corn_current_year_1000m) + 
                     scale(tmean_f) * scale(prop_nat_current_year_1000m) + 
                     cover_crop * scale(prop_corn_current_year_1000m) + 
                     cover_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(prop_corn_current_year_1000m) + 
                     previous_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(tmean_f) + 
                     scale(tmean_f) * cover_crop + 
                     (1 | field_id), data = adult_features)

summary(model7)

```

```{r}

options(na.action = "na.fail")
model5_dredge <- dredge(model5)
nrow(model5_dredge)
model5_dredge[1,]

best5 <- get.models(model5_dredge, delta==0)[[1]]
summary(best5)

```

```{r}

options(na.action = "na.fail")
model6_dredge <- dredge(model6)
nrow(model6_dredge)
model6_dredge[1,]

best6 <- get.models(model6_dredge, delta==0)[[1]]
summary(best6)

```


```{r}

model8 <- glmer.nb(total_flies ~ scale(date_collected_numeric) + 
                     cover_crop + 
                     previous_crop + 
                     scale(tmean_f) + 
                     scale(prop_corn_current_year_1000m) + 
                     scale(prop_nat_current_year_1000m) + 
                     scale(planting_date) + 
                     scale(tmean_f) * scale(prop_corn_current_year_1000m) + 
                     scale(tmean_f) * scale(prop_nat_current_year_1000m) + 
                     cover_crop * scale(prop_corn_current_year_1000m) + 
                     cover_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(prop_corn_current_year_1000m) + 
                     previous_crop * scale(prop_nat_current_year_1000m) + 
                     previous_crop * scale(tmean_f) + 
                     scale(tmean_f) * cover_crop + 
                     (1 | field_id), data = adult_features)

summary(model8)

```

```{r}

options(na.action = "na.fail")
model8_dredge <- dredge(model8)
nrow(model8_dredge)
model8_dredge[1,]

best8 <- get.models(model8_dredge, delta==0)[[1]]
summary(best8)

```

```{r}

quartzFonts(avenir = c("Avenir Book", "Avenir Black", "Avenir Book Oblique", "Avenir Black Oblique"))
par(family = "avenir")

corn_effect <- Effect("prop_corn_current_year_1000m", best8)
plot(corn_effect)

```

```{r}

nat_effect <- Effect("prop_nat_current_year_1000m", best8)
plot(nat_effect)

```

```{r}

temp_effect <- Effect("tmean_f", best8)
plot(temp_effect)

```

```{r}

date_effect <- Effect("date_collected_numeric", best8)


plot(date_effect, axes=list(x=list(date_collected_numeric=list(lab="Date",
                                                 ticks=list(at=levels2dates(date_effect, "date_collected_numeric", "1970-01-01"))),
                                   rotate=45)), main="Date Effect")

```

```{r}

prev_crop_effect <- Effect(c('previous_crop'), best8)
plot(prev_crop_effect)

```

```{r}

temp_cc_effect <- Effect(c("tmean_f", 'cover_crop'), best8)
plot(temp_cc_effect)

```

```{r}

temp_corn_effect <- Effect(c('prop_corn_current_year_1000m', "tmean_f"), best8)
plot(temp_corn_effect)

```

```{r}

temp_nat_effect <- Effect(c('prop_nat_current_year_1000m', "tmean_f"), best8)
plot(temp_nat_effect)

```

```{r}

PARTIAL_MODEL <- Effect('prop_nat_current_year_1000m', partial.residuals = TRUE, mod = best8);
plot(PARTIAL_MODEL);

```



```{r}

test_ag_model <- glmer.nb(total_flies ~ cover_crop + previous_crop + scale(date_collected_numeric) +  
    scale(prop_ag_current_year_1000m) + scale(prop_nat_current_year_1000m) +  
    scale(tmean_f) + (1 | field_id) + cover_crop:scale(tmean_f) +  
    scale(prop_ag_current_year_1000m):scale(tmean_f) + scale(prop_nat_current_year_1000m):scale(tmean_f), data=adult_features)

summary(test_ag_model)

```

```{r}

adult_features_early <- adult_features %>% filter(week < 21)
adult_features_early

```

```{r}

boruta_early <- Boruta(total_flies ~ ., data = na.exclude(adult_features_early), doTrace = 2, maxRuns = 500)
print(boruta_early)

png("boruta.png", width = 8, height = 6, units = "in", res = 300)
plot(boruta_early, las = 2, cex.axis = 0.35)



```






```{r, fig.width=4,fig.height=4}
  
quartzFonts(avenir = c('Avenir Book', 'Avenir Black', 'Avenir Book Oblique', 'Avenir Black Oblique'))

model_effects <- effect("ave_temp_f_1_week", model)


par(bg = '#ffefb4', family = 'avenir')

plot(model_effects, main='Average Weekly Temperature (°F) Effect Plot', xlab='Average Weekly Temperature (°F)', ylab=expression(paste("Number of Adult ", italic("D. platura")))) 


```

```{r, fig.width=4,fig.height=4}

model_effects <- effect("rain_inches_1_week", model)
plot(model_effects, main='Total Weekly Rainfall Effect Plot', xlab='Total Weekly Rainfall (Inches)', ylab=expression(paste("Number of Adult ", italic("D. platura"))), cex=5)

```

```{r, fig.width=4,fig.height=4}

model_effects <- effect("corn_prop_5.year_500", model)
plot(model_effects, main='Proportion of Corn in Landscape Effect Plot', xlab='Proportion Corn in the Landscape (%)', ylab=expression(paste("Number of Adult ", italic("D. platura"))), cex=5)

```

```{r, fig.width=4,fig.height=4}

model_effects <- effect("organic_matter_percent", model)
plot(model_effects, main='Soil Organic Matter (%) Effect Plot', xlab='Soil Organic Matter (%)', ylab=expression(paste("Number of Adult ", italic("D. platura"))), cex=5)

```

```{r, fig.width=4,fig.height=4}

model_effects <- effect("cover_crop", model)
plot(model_effects, main='Cover Crop Effect Plot', xlab='Cover Crop', ylab=expression(paste("Number of Adult ", italic("D. platura"))), cex=5)

```


```{r, fig.width=16,fig.height=8}

#Visualize significant variables

above_temp <- adult_features %>% filter(ave_temp_f_1_week > 39)

ggplot(above_temp, aes(x=ave_temp_f_1_week, y=total_scm)) + 
    geom_point(color = 'white') + 
  geom_smooth(method=lm , color="gold", se=TRUE) + theme(
  panel.background = element_rect(fill = "black", color = "NA",
                                size = 2, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "grey"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "grey"),
  ) + 
  theme(plot.background = element_rect(fill = "black", color='NA'), 
        title = element_text(size = 45, colour = "white"), 
        text = element_text(family = 'Avenir'), 
        axis.text.x = element_text(color='white', size = 30),
        axis.text.y = element_text(color='white', size = 30)) + 
  ggtitle(expression(paste("Adult ", italic("D. platura"), " Abundance vs. Average Weekly Temperature"))) +
  xlab("Average Weekly Temperature (°F)") + 
  ylab(expression(paste("Number of Adult ", italic("D. platura"))))

```

```{r, fig.width=16,fig.height=8}

#Visualize significant variables

ggplot(adult_features, aes(x=rain_inches_1_week, y=total_scm)) + 
    geom_point(color = 'white') + 
  geom_smooth(method=lm , color="gold", se=TRUE) + theme(
  panel.background = element_rect(fill = "black", color = "NA",
                                size = 2, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "grey"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "grey"),
  ) + 
  theme(plot.background = element_rect(fill = "black", color='NA'), 
        title = element_text(size = 24, colour = "white"), 
        text = element_text(family = 'Avenir'), 
        axis.text.x = element_text(color='white', size = 16),
        axis.text.y = element_text(color='white', size = 16)) + 
  ggtitle(expression(paste("Adult ", italic("D. platura"), " Abundance vs. Total Weekly Rainfall (Inches)"))) +
  xlab("Total Weekly Rainfall (Inches)") + 
  ylab(expression(paste("Number of Adult ", italic("D. platura"))))

```


```{r, fig.width=16,fig.height=8}

#Visualize significant variables

ggplot(adult_features, aes(x=corn_prop_5.year_500, y=total_scm)) + 
    geom_point(color = 'white') + 
  geom_smooth(method=lm , color="gold", se=TRUE) + theme(
  panel.background = element_rect(fill = "black", color = "NA",
                                size = 2, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "grey"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "grey"),
  ) + 
  theme(plot.background = element_rect(fill = "black", color='NA'), 
        title = element_text(size = 24, colour = "white"), 
        text = element_text(family = 'Avenir'), 
        axis.text.x = element_text(color='white', size = 16),
        axis.text.y = element_text(color='white', size = 16)) + 
  ggtitle(expression(paste("Adult ", italic("D. platura"), " Abundance vs. Proportion Corn in the Landscape (%)"))) +
  xlab("Proportion Corn in the Landscape (%)") + 
  ylab(expression(paste("Number of Adult ", italic("D. platura"))))

```


```{r, fig.width=16,fig.height=8}

#Visualize significant variables

ggplot(adult_features, aes(x=organic_matter_percent, y=total_scm)) + 
    geom_point(color = 'white') + 
  geom_smooth(method=lm , color="gold", se=TRUE) + theme(
  panel.background = element_rect(fill = "black", color = "NA",
                                size = 2, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "grey"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "grey"),
  ) + 
  theme(plot.background = element_rect(fill = "black", color='NA'), 
        title = element_text(size = 24, colour = "white"), 
        text = element_text(family = 'Avenir'), 
        axis.text.x = element_text(color='white', size = 16),
        axis.text.y = element_text(color='white', size = 16)) + 
  ggtitle(expression(paste("Adult ", italic("D. platura"), " Abundance vs. Soil Organic Matter (%)"))) +
  xlab("Soil Organic Matter (%)") + 
  ylab(expression(paste("Number of Adult ", italic("D. platura"))))

```

```{r, fig.width=16,fig.height=8}

#Visualize significant variables

adult_features_mod <- adult_features
adult_features_mod$cover_crop[adult_features$cover_crop == 'Partial'] <- 'Yes'

ggplot(adult_features_mod, aes(x=cover_crop, y=total_scm)) + 
    geom_bar(stat = 'identity', fill='grey') + 
  theme(panel.background = element_rect(fill = "black", color = "NA",
                                size = 2, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "grey"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "grey"),
  ) + 
  theme(plot.background = element_rect(fill = "black", color='NA'), 
        title = element_text(size = 24, colour = "white"), 
        text = element_text(family = 'Avenir'), 
        axis.text.x = element_text(color='white', size = 16),
        axis.text.y = element_text(color='white', size = 16)) + 
  ggtitle(expression(paste("Adult ", italic("D. platura"), " Abundance vs. Cover Crop"))) +
  xlab("Cover Crop") + 
  ylab(expression(paste("Number of Adult ", italic("D. platura"))))

```


```{r}

#Take out NS variables and do 2-way interaction for everything 

model <- glmer.nb(total_scm ~ (cover_crop + ave_temp_f_1_week + rain_inches_1_week + organic_matter_percent + corn_prop_5.year_500)^2 + (1 | record_id), data = adult_features)

summary(model)

```

```{r}

interact_plot(model, pred = ave_temp_f_1_week, modx = cover_crop)

```

```{r}

interact_plot(model, pred = ave_temp_f_1_week, modx = rain_inches_1_week)

```

```{r}

interact_plot(model, pred = corn_prop_5.year_500, modx = organic_matter_percent)

```


```{r}

peak_adults <- read.delim("Data/2023_adult_peak_features.csv", sep = ",")
peak_adults

```


```{r}

peak_adults <- peak_adults %>%
  mutate(collection_date = as.Date(collection_date, '%Y-%m-%d')) %>%
  mutate_at(c('record_id', 'data_collector', "previous_crop", "cover_crop", "manure", "tillage", "ny_soils_0", "ny_soils_01", "muid","hsg", "hsgint"), as.factor) %>%
  dplyr::select(-c(X, n_scm_i_m, n_scm_i_f, n_scm_o_m, n_scm_o_f, n_d_florilega_i, n_d_florilega_o, total_f_scm, total_m_scm))

```

```{r}

plot(fitdist(peak_adults$total_scm,"norm"))

```

```{r}

boruta <- Boruta(total_scm ~ ., data = na.exclude(peak_adults), doTrace = 2, maxRuns = 500)
print(boruta)

plot(boruta, las = 2, cex.axis = 0.7)

```

```{r}

features <- getSelectedAttributes(boruta, withTentative = F)
features

```

```{r}

model <- lm(total_scm ~ scale(collection_date) + cover_crop + manure + tillage + ave_temp_f_1_week + rain_inches_1_week + vpd_min_1_week + corn_prop_5.year_500 + soybean_prop_5.year_500 + total_nat_prop_5.year_500 + organic_matter_percent, data = peak_adults, family = gaussian)
summary(model)

```


```{r}

#Take out NS variables and do 2-way interaction for everything 

model <- lm(total_scm ~ (cover_crop + corn_prop_5.year_500)^2, data = peak_adults)

summary(model)

```

```{r}

#Take out NS variables and do 2-way interaction for everything, including marginally significant terms

model <- lm(total_scm ~ (cover_crop + corn_prop_5.year_500 + vpd_min_1_week + total_nat_prop_5.year_500)^2, data = peak_adults)

summary(model)

```

```{r}
plot_model(model)

```

```{r}
plot(peak_adults$corn_prop_5.year_500, peak_adults$total_scm)
abline(lm(peak_adults$total_scm ~ peak_adults$corn_prop_5.year_500))

```
